# Generated by Django 3.2.18 on 2023-04-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTLayananKarisKarsu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orang', models.CharField(max_length=100)),
                ('opd', models.CharField(max_length=255)),
                ('veropd', models.DateField()),
                ('verbkd', models.DateField()),
                ('verbkn', models.DateField()),
                ('tolak', models.DateField()),
                ('selesai', models.DateField()),
                ('siapa', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 't_layanan_karis_karsu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelTOpd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField()),
                ('nama', models.CharField(max_length=255)),
                ('leader', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 't_opd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelTPasangan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('orang', models.CharField(max_length=100)),
                ('akta', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_nikah', models.CharField(blank=True, max_length=100, null=True)),
                ('status_nikah', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 't_pasangan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelTRiwayatPangkat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orang', models.CharField(max_length=100)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis', models.CharField(blank=True, max_length=100, null=True)),
                ('tmt', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('simbol', models.CharField(blank=True, max_length=100, null=True)),
                ('mktahun', models.IntegerField(blank=True, null=True)),
                ('mkbulan', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_riwayat_pangkat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TJenisPengajuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('keterangan', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 't_jenis_pengajuan',
                'managed': False,
            },
        ),
    ]
