# Generated by Django 4.1.7 on 2023-04-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTDataUtama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('nip', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis_asn', models.CharField(blank=True, max_length=100, null=True)),
                ('nik', models.CharField(blank=True, max_length=100, null=True)),
                ('pangkat', models.CharField(blank=True, max_length=100, null=True)),
                ('golongan', models.CharField(blank=True, max_length=100, null=True)),
                ('eselon', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis_jabatan', models.CharField(blank=True, max_length=100, null=True)),
                ('jabatan', models.CharField(blank=True, max_length=255, null=True)),
                ('instansi', models.CharField(blank=True, max_length=100, null=True)),
                ('perangkat_daerah', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_kerja', models.CharField(blank=True, max_length=255, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=255, null=True)),
                ('tgl_lahir', models.CharField(blank=True, max_length=255, null=True)),
                ('gol_darah', models.CharField(blank=True, max_length=255, null=True)),
                ('telpon', models.CharField(blank=True, max_length=255, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, max_length=255, null=True)),
                ('status_pernikahan', models.CharField(blank=True, max_length=255, null=True)),
                ('agama', models.CharField(blank=True, max_length=255, null=True)),
                ('alamat', models.CharField(blank=True, max_length=255, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=255, null=True)),
                ('kabupaten', models.CharField(blank=True, max_length=255, null=True)),
                ('provinsi', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('glr_belakang', models.CharField(blank=True, max_length=255, null=True)),
                ('glr_depan', models.CharField(blank=True, max_length=255, null=True)),
                ('tmt_cpns', models.CharField(blank=True, max_length=255, null=True)),
                ('bup', models.IntegerField()),
                ('kel_jab', models.IntegerField()),
            ],
            options={
                'db_table': 't_data_utama',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelTLayananKarisKarsu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orang', models.CharField(max_length=100)),
                ('opd', models.CharField(max_length=255)),
                ('pendukung', models.ImageField(upload_to='media')),
                ('formulir', models.ImageField(upload_to='media')),
                ('veropd', models.DateField()),
                ('verbkd', models.DateField()),
                ('verbkn', models.DateField()),
                ('tolak', models.DateField()),
                ('selesai', models.DateField()),
                ('siapa', models.CharField(max_length=100)),
                ('code', models.ImageField(blank=True, null=True, upload_to='code')),
            ],
            options={
                'db_table': 't_layanan_karis_karsu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelTOpd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField()),
                ('nama', models.CharField(max_length=255)),
                ('leader', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 't_opd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelTPasangan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('orang', models.CharField(max_length=100)),
                ('akta', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_nikah', models.CharField(blank=True, max_length=100, null=True)),
                ('status_nikah', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 't_pasangan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelTRiwayatPangkat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orang', models.CharField(max_length=100)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis', models.CharField(blank=True, max_length=100, null=True)),
                ('tmt', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('simbol', models.CharField(blank=True, max_length=100, null=True)),
                ('mktahun', models.IntegerField(blank=True, null=True)),
                ('mkbulan', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_riwayat_pangkat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelTUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orang', models.CharField(db_column='nip', max_length=100)),
                ('role', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 't_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TJenisPengajuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('keterangan', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 't_jenis_pengajuan',
                'managed': False,
            },
        ),
    ]
