# Generated by Django 4.1.7 on 2023-03-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTRiwayatPangkat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100, null=True)),
                ('jenis', models.CharField(max_length=100, null=True)),
                ('tmt', models.DateField()),
                ('status', models.CharField(max_length=100, null=True)),
                ('simbol', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 't_riwayat_pangkat',
                'managed': False,
            },
        ),
    ]
