# Generated by Django 3.1.6 on 2023-03-31 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTOpd',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('leader', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 't_opd',
                'managed': False,
            },
        ),
    ]
