# Generated by Django 4.1.7 on 2023-05-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRiwayatJabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_nama_jabatan', models.CharField(max_length=255)),
                ('field_jns_jabatan', models.CharField(max_length=255)),
                ('field_tmt_jabatan', models.DateField()),
                ('field_file_skk', models.CharField(max_length=255)),
                ('moderation_state', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ModelRiwayatJabatan',
                'managed': False,
            },
        ),
    ]
